{{- if .Values.githubRunnerToken }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runnerTokenSecretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
  {{- $encodedRunnerToken := (required ".Values.githubRunnerToken must be set" .Values.githubRunnerToken) | b64enc | quote }}
  {{ .Values.runnerTokenSecretKey }}: {{ $encodedRunnerToken }}

{{- end }}
